# actuator info
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'
# cloud setting
eureka:
  client:
    service-url:
      defaultZone: ${SPRING_EUREKA_CLIENT_URL:http://registry-service:8761/eureka/}
  instance:
    prefer-ip-address: true
